### PR TITLE
bump oauth dependency

### PR DESCRIPTION
**Pull request by GabrielMahan**

### CODE REVIEW

**Comment by YoranBrondsema** [comment]
Yes, please get this merged.

**Comment by YoranBrondsema** [comment]
@meliaj Is it possible to publish a new release with this change? Thanks!

**Comment by meliaj** [comment]
I don't have permission to push the gem. I'll need to track down the original Clever account that is an owner on the gem. Stay tuned...

**Comment by meliaj** [comment]
@YoranBrondsema I have published a new version now!

**Comment by YoranBrondsema** [comment]
Awesome, great for the quick turnaround @meliaj!

**Pull request merged**
